services:
  - type: web
    name: waretracker-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn -w 4 'run:create_app()'
    envVars:
      - key: DATABASE_URL
        value: sqlite:///warehouse.db
