"""Added soft deletes to product model

Revision ID: 242363396dfa
Revises: c1d4b820f088
Create Date: 2025-06-29 01:44:16.984528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242363396dfa'
down_revision = 'c1d4b820f088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
