"""Add is_active to business_locations

Revision ID: 37c8d99e39f4
Revises: 87b608ca7a48
Create Date: 2025-06-27 18:07:20.603233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c8d99e39f4'
down_revision = '87b608ca7a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_level', sa.Integer(), nullable=False))

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('transfer_type')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_level')

    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
