"""Add is_active to business_locations.

Revision ID: cd52d63d3246
Revises: 2f6087716a7d
Create Date: 2025-06-27 00:03:12.923884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import true


# revision identifiers, used by Alembic.
revision = 'cd52d63d3246'
down_revision = '2f6087716a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
