"""next safe migration

Revision ID: d37a7cb191d3
Revises: bbe6366291e6
Create Date: 2025-06-27 16:17:07.241426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37a7cb191d3'
down_revision = 'bbe6366291e6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stock_level', sa.Integer(), nullable=False, server_default=sa.text("0"))
        )

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('transfer_type', sa.String(length=10), nullable=False, server_default=sa.text("'IN'"))
        )
        batch_op.add_column(
            sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.alter_column(
            'location_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('transfer_type')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
